### GENERAL SETTINGS ###

# Site settings
title: SOLID.
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/paginaSCEIS" #important: start with /
url: "http://sociedadceis.sceis"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: envelope
    url: mailto:sceis.ucbcba@gmail.com
  - title: linkedin
    url: 
  - title: facebook
    url: https://www.facebook.com/SCEIS-UCB-Sociedad-Cient%C3%ADfica-de-Ingenier%C3%ADa-de-Sistemas-102775131962276
  - title: github
    url: https://github.com/SociedadCEIS

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Calle M. Marquez esquina Parque Jorge Trigo Andia,
    - Campus Tupuraya, 
    - Cochabamba - Bolivia.
email: sceis.ucbcba@gmail.com


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Dr. Juan Pablo Sandoval 
    position: Docente asesor
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
 
  - name: Alejandra Cossio 
    position: Presidente
    img: team02.jpg
    social:
      - title: envelope
        url: mailto:alejandra.cossio.ch@gmail.com
      - title: linkedin
        url: https://www.linkedin.com/in/alejandra-cossio-chavalier/
  - name: Jeymi Paulas
    position: Vice-Presidente
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Daniel Camacho Santa Cruz
    position: Tesorero
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Pamela Navia
    position: Coordinadora
    img: team06.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Denilson Fiesta
    position: Secretario
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Somos un grupo de estudiantes de la carrera de Ing. de Sistemas cuyo objetivo es realizar, publicar y diseminar investigaciones científicas de alto impacto en ciencias de la computación."

